sudo: false
dist: focal
language: python
python:
- "3.10.2"
before_install:
- pip3.10 install -r requirements.txt
- pip3.10 install -e .
script: pytest -m "not compiled" --cov=pythonwhat
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: YSxFsCIO8OW/8NyVtVPjvWceAscKcjX3PpDqU8/GwP6TkpE/ORZbc2Gc5zZz6arq/zormtGvv85fxc+mub9GqRdavPtNDaeq1QgzDIWfXOHAoQ5jWBwfXQz/MvP9YS3yk5uex1usga/nlm1Q6Am7RwYnttpNv3TRRJbDDMOc9wzYa+lHYZBlvaispewgusz6uXzeO3M1Aj+KwNSfwMU8yAJNhFGG5mk329yv8EGKMXO9nuTYOLm3JF1E1aiZD0bcVDETvTGq9GyWQG+Od3zvXDpQW0B0rHgRmXCH7AVdHIAxletYf7jEhFmNh+kn8yXxtcnuRo6E90HMGPGU91ErF5NDWpOlCTbdSNj2oGHDZFWiIw717RBWMz7MyfV8aeseL6HKNu+jnDPm+1ANSpzI3V+DUexsKynPDzRT2kZsM5jSxyuncx8oNsmaqt9eRL9vOhzD4tBP6oRI8tPtQMB/4zXv12ihFYc5fYARRgx5jlAxqwYfwvsdF49Sna9XGiubQeJOPs1tDni/eXZrr7ey0Mj8r7eJyxqXcsXqYq1F4jDyijubGcYJyhPXU9F64vlPel/Kvg7Z5c0XOu/6yptoVaapSM3v7NYk65hvGq+GBtX4IexwaZousOVeHMHavXVU5HL4+t7UrFxLKnsZIGZtRVT2nuUV5P/fcUjeF0uw70A=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/pythonwhat
  skip_upload_docs: true
